# FZF theme - auto-generated by theme switcher
# Current mode: light
status is-interactive; or return

set -Ux FZF_DEFAULT_OPTS "--color=bg+:#e7e7e7,bg:#fafafa,spinner:#a626a4,hl:#e45649 --color=fg:#383a42,header:#4078f2,info:#a626a4,pointer:#4078f2 --color=marker:#50a14f,fg+:#383a42,prompt:#a626a4,hl+:#e45649 --color=selected-bg:#dfdfdf --color=border:#c6c7c7,label:#383a42"
