# FZF theme - auto-generated by theme switcher
# Current mode: light
status is-interactive; or return

set -Ux FZF_DEFAULT_OPTS "--color=bg+:#c6daff,bg:#ffffff,spinner:#721045,hl:#a60000 --color=fg:#000000,header:#0031a9,info:#721045,pointer:#0031a9 --color=marker:#006800,fg+:#000000,prompt:#721045,hl+:#a60000 --color=selected-bg:#dfa0f0 --color=border:#9f9f9f,label:#000000"
