# FZF theme - auto-generated by theme switcher
# Current mode: light
[[ $- != *i* ]] && return

export FZF_DEFAULT_OPTS="--color=bg+:#eeeeee,bg:#ffffff,spinner:#999999,hl:#cc0000 --color=fg:#222222,header:#444444,info:#999999,pointer:#222222 --color=marker:#222222,fg+:#222222,prompt:#555555,hl+:#cc0000 --color=selected-bg:#e0e0e0 --color=border:#cccccc,label:#222222"
